### ISSUE TITLE
crash on launch (1.15.2-31.1.13)

### ISSUE THREAD

**Issue by SDUBZ** [thraaawn/BonsaiTrees#152]
forge: 1.15.2-31.1.13
BonsaiTrees-2.1.2.6

crash report:
[crash-2020-02-18_07.23.42-client.txt](https://github.com/thraaawn/BonsaiTrees/files/4216060/crash-2020-02-18_07.23.42-client.txt)

logs:
[latest.log](https://github.com/thraaawn/BonsaiTrees/files/4216062/latest.log)

**Comment by davenonymous** [comment]
See #146, this is not a bonsai trees issue.
Your actual issue is further above in the log:
```
[07:23:37] [modloading-worker-1/ERROR]: Failed to create mod instance. ModID: mysticalagriculture, class com.blakebr0.mysticalagriculture.MysticalAgriculture
com.electronwill.nightconfig.core.io.ParsingException: Invalid bare key: $??m??mo?L?D??;?%g??w??????ovH0??a?5??*????l??S?iy?r?O7????%L
	at com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:175) ~[toml-3.6.2.jar:?]
	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145) ~[toml-3.6.2.jar:?]
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55) ~[toml-3.6.2.jar:?]
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44) ~[toml-3.6.2.jar:?]
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.2.jar:?]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.2.jar:?]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.2.jar:?]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.2.jar:?]
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.2.jar:?]
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.2.jar:?]
	at com.blakebr0.cucumber.helper.ConfigHelper.load(ConfigHelper.java:15) ~[?:3.0.1]
	at com.blakebr0.mysticalagriculture.MysticalAgriculture.<init>(MysticalAgriculture.java:77) ~[?:3.0.0]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:131) [?:31.1]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2226/779998468.accept(Unknown Source) [?:31.1]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2225/772065437.accept(Unknown Source) [?:1.8.0_51]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2225/772065437.accept(Unknown Source) [?:1.8.0_51]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) [?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2640/633131350.accept(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_51]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
```
Looks like your config files are somehow broken.
