### ISSUE TITLE
Crash on launch[FORGE 1.15.2-31.1.18]

### ISSUE THREAD

**Issue by SDUBZ** [thraaawn/BonsaiTrees#158]
Forge: FORGE 1.15.2-31.1.18
Bonsai: BonsaiTrees-2.1.2.6

crash:
[crash-2020-02-29_16.59.03-client.txt](https://github.com/thraaawn/BonsaiTrees/files/4269986/crash-2020-02-29_16.59.03-client.txt)

logs:
[latest.log](https://github.com/thraaawn/BonsaiTrees/files/4269987/latest.log)

**Comment by davenonymous** [comment]
Not a bonsai trees issue.
Your actual error from the latest.log is attached below. Not sure which mod is providing the `coremods/remove-enchantment-limit.js` coremod. You'll have to figure that out and then report this issue to that mod.
```
[16:58:42] [Render thread/ERROR]: Error occurred applying transform of coremod coremods/remove-enchantment-limit.js function edit_block_event
jdk.nashorn.internal.runtime.ECMAException: ReferenceError: "foundNode" is not defined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291) ~[nashorn.jar:?]
	at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:914) ~[nashorn.jar:?]
	at jdk.nashorn.internal.scripts.Script$Recompilation$89$723A$\^eval\_.patch_RepairContainer_updateRepairOutput(<eval>:33) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$Recompilation$87$351A$\^eval\_.initializeCoreMod$transformer(<eval>:12) ~[?:?]
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:638) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:229) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:387) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:110) ~[nashorn.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModMethodTransformer.runCoremod(CoreModMethodTransformer.java:18) ~[coremods-2.0.0-milestone.1.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModMethodTransformer.runCoremod(CoreModMethodTransformer.java:10) ~[coremods-2.0.0-milestone.1.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModBaseTransformer.transform(CoreModBaseTransformer.java:38) [coremods-2.0.0-milestone.1.jar:?]
	at cpw.mods.modlauncher.TransformerHolder.transform(TransformerHolder.java:41) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.performVote(ClassTransformer.java:168) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:106) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:239) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:126) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) [modlauncher-5.0.0-milestone.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at net.minecraft.block.Blocks.<clinit>(Blocks.java:339) [?:?]
	at net.minecraft.util.registry.Registry.lambda$static$3(Registry.java:91) [?:?]
	at net.minecraft.util.registry.Registry$$Lambda$577/2062755811.get(Unknown Source) [?:?]
	at net.minecraft.util.registry.Registry.lambda$static$40(Registry.java:261) [?:?]
	at net.minecraft.util.registry.Registry$$Lambda$614/1238145834.accept(Unknown Source) [?:?]
	at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:663) [?:1.8.0_51]
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:260) [?:?]
	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:34) [?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:353) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.18.jar:31.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$419/42338572.call(Unknown Source) [forge-1.15.2-31.1.18.jar:31.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?]
```
