### ISSUE TITLE
Exception in event handler disables JEI after Biomes O' Plenty update

### ISSUE THREAD

**Issue by NikolaiSchreier** [thraaawn/BonsaiTrees#200]
I recently updated my world and among the mods updated was Biome O' Plenty. The new version no longer features the ethereal_forest biome and all related blocks. Now I get the following (client) exception when joining the world:
```
[Render thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: The property axis is not valid for block biomesoplenty:ethereal_log
	Index: 3
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2142/106350019@33255547
		2: net.minecraftforge.eventbus.EventBus$$Lambda$2142/106350019@311ce8c0
		3: ASM: com.davenonymous.bonsaitrees2.setup.ForgeEventHandlers@765192a4 recipesUpdated(Lnet/minecraftforge/client/event/RecipesUpdatedEvent;)V
		4: ASM: blusunrize.immersiveengineering.common.crafting.RecipeReloadListener@3d427fee onRecipesUpdated(Lnet/minecraftforge/client/event/RecipesUpdatedEvent;)V
		5: net.minecraftforge.eventbus.EventBus$$Lambda$2142/106350019@5b1965ea
com.google.gson.JsonSyntaxException: The property axis is not valid for block biomesoplenty:ethereal_log
	at com.davenonymous.libnonymous.utils.BlockStateSerializationHelper.deserializeBlockState(BlockStateSerializationHelper.java:219)
	at com.davenonymous.libnonymous.serialization.MultiBlockModelSerializer.getReferenceMapV3(MultiBlockModelSerializer.java:48)
	at com.davenonymous.libnonymous.serialization.MultiBlockModelSerializer.deserializeV3(MultiBlockModelSerializer.java:81)
	at com.davenonymous.libnonymous.serialization.MultiBlockModelSerializer.deserialize(MultiBlockModelSerializer.java:36)
	at com.davenonymous.libnonymous.serialization.MultiBlockModelSerializer.deserialize(MultiBlockModelSerializer.java:15)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.davenonymous.bonsaitrees2.render.TreeModels.init(TreeModels.java:28)
	at com.davenonymous.bonsaitrees2.setup.ForgeEventHandlers.recipesUpdated(ForgeEventHandlers.java:38)
```

This completely disables JEI. I see no way to fix this other than starting the server once without the Bonsai Trees mod to remove all references to obsolete blocks.

**Comment by NikolaiSchreier** [comment]
Scratch my last comment, as even that doesn't seem to work. The only thing I found was creating a new, untainted single player world and starting that first.

**Comment by NikolaiSchreier** [comment]
Sorry, forgot to add the relevant versions:
Upgraded from:
Minecraft 1.14.4, Forge 28.2.16
Bonsai Trees 2.0.2.35
Biomes O' Plenty 1.14.4-9.0.0.262-universal

Upgraded to:
Minecraft 1.15.2, Forge 31.2.21
Bonsai Trees 2.1.2.6
Biomes O' Plenty 1.15.2-10.0.0.366-universal

**Comment by davenonymous** [comment]
Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
